---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdep
  labels:
    app: testdep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testdep
  template:
    metadata:
      labels:
        app: testdep
    spec:
      containers:
      - name: testdep
        image: testdep:lukeg
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: testdep-service
spec:
  selector:
    app: testdep 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
